progmatic-fs-2023/club-project

client/src/components/AllServices.jsx, client/src/components/Layout.jsx, client/src/components/ServiceCard.jsx, client/src/index.css
https://progmaticfs4.atlassian.net/jira/software/projects/CLUB/boards/2?selectedIssue=CLUB-43
- Navbar színének a módosítása
- Services oldalon a link módosítása
- Gombok színének módosítása hover esetén
=> [CLUB-43] navbar szín módosítás

client/src/App.jsx, client/src/components/EventCard.jsx, client/src/components/Layout.jsx, client/src/components/MainCarousel.jsx, client/src/components/SearchBar.jsx, client/src/components/ServiceCard.jsx, client/src/index.scss, client/src/main.jsx, client/src/pages/Event.jsx, client/src/pages/Home.jsx, client/src/pages/Service.jsx
https://progmaticfs4.atlassian.net/jira/software/projects/CLUB/boards/2?selectedIssue=CLUB-47
- Színek egységesítése
- SCSS fájl letisztázása
=> [CLUB-47] CSS colors fix

client/src/App.jsx, client/src/components/ForgotPasswordModal.jsx, client/src/components/Layout.jsx, client/src/components/LoginModal.jsx, client/src/contexts/AuthContext.jsx, client/src/main.jsx, client/src/pages/NewPasswordPage.jsx, server/src/controllers/auth.controller.js, server/src/controllers/users.controller.js, server/src/routes/api.route.js, server/src/services/email.service.js, server/src/services/users.service.js
- login után, ha frissítjük az oldalt, bejelentkezve marad
- loginkor ellenőrzi az adatbázist és csak akkor lép be, ha egyezés van
- Forgot password modal és link, valamint a newpasswordpage
=> [CLUB-83] login and more

client/src/components/FilterBar.jsx, client/src/components/Layout.jsx, client/src/components/MainCarousel.jsx, client/src/index.scss, client/src/pages/AdminMember.jsx, client/src/pages/Events.jsx, client/src/pages/Membership.jsx, client/src/pages/Services.jsx, server/src/services/db.service.js
- membership page responsivity fix 
- main carousel responsivity fix
- minor responsivity issues fixes
=> [CLUB-109] responsivity bugs fixes

client/src/components/AdminEvents.jsx, client/src/pages/Events.jsx, server/src/controllers/events.controller.js, server/src/routes/events.route.js, server/src/services/events.service.js
- event search bar működik
- lejárt események nem jelennek meg
- adminból eventek módosíthatóak
=> event és eventadmin fixek

client/src/pages/Event.jsx, client/src/pages/Service.jsx
Servive és Event oldalakon történt módosítások:
- A foglalás gomb inaktív, amíg nincs valaki bejelentkezve
- Gombokra ikon elhelyezése
- Gombok módosítása és formázása
- Responsivitás módosítása
=> [CLUB-149] booking button modification

client/src/components/BookingServiceSelector.jsx, client/src/components/BookingWeeklyView.jsx, client/src/components/CurrentBookingWindow.jsx, client/src/components/ForgotPasswordModal.jsx, client/src/components/LoginFeedbackModal.jsx, client/src/components/ProfileCard.jsx, client/src/components/RegistrationModal.jsx, client/src/pages/AdminMember.jsx, client/src/pages/Booking.jsx, server/src/controllers/booking.controller.js, server/src/routes/booking.route.js, server/src/services/booking.service.js
- send a POST request when the 'Confirm Booking' button is clicked
- membership settings come from context
- minor responsivity issues fixes
=> [CLUB-138] booking confirm button

client/src/components/AllEvents.jsx, client/src/components/AllServices.jsx, client/src/components/EventCard.jsx, client/src/components/ServiceCard.jsx, client/src/index.scss, client/src/pages/Event.jsx, client/src/pages/Membership.jsx, client/src/utils/dateUtils.js, server/src/services/services.service.js
- add a corner ribbon to membership and services cards. Information is sourced from the database (CLUB-140)
- update services on membership cards (CLUB-141)
- set the time on event cards to 24h
=> [CLUB-141] add to membership and services cards a corner ribbon

client/src/App.jsx, client/src/components/AdminMembers.jsx, client/src/components/AdminSidebar.jsx, client/src/components/AllServices.jsx, client/src/components/ServiceCard.jsx, client/src/index.scss, client/src/pages/AdminMember.jsx, client/src/pages/Service.jsx, client/src/pages/Services.jsx
- sync service cards and booking button visibility with the current membership
- delete dashboard page
=> [CLUB-156] sync services visibility with the current membership

client/src/components/AboutUsCharity.jsx, client/src/components/FilterBar.jsx, client/src/pages/Events.jsx, client/src/pages/Home.jsx
- remove the services slider from the home page
- place the charity component on the home page
- create a checkbox to filter available events
=> [CLUB-50] fiter for available events

client/src/components/AdminMemberSearch.jsx, client/src/components/AdminMembers.jsx, client/src/components/AdminServiceBookingSearch.jsx, client/src/components/AdminServiceBookings.jsx, client/src/pages/Events.jsx
- create a filter bar for the admin services page
- fix the filter bar bug on the admin users page
- fix the search bug on the frontend events page (frontend )
=> [CLUB-144] create filterbar in admin services booking page

client/src/pages/Membership.jsx, client/src/pages/Service.jsx, server/src/controllers/users.controller.js, server/src/routes/membership.route.js, server/src/services/users.service.js
- the user can change the level of membership (frontnend)
- backend (PUT request)
- the data is updating in database (membership and is_payed)
=> [CLUB-29] the user can change the level of membership

client/src/App.jsx, client/src/components/AdminHeeder.jsx, client/src/components/AdminMembers.jsx, client/src/components/Layout.jsx, client/src/components/ProtectedRoute.jsx
- created a protected route for the admin page
- to display the logged-in admin's name on the admin page
- if a user logs in with an admin role, a button will appear that navigate to the admin page
=> [CLUB-58] created a protected route for the admin page

client/src/components/AdminBookings.jsx, client/src/components/AdminHeeder.jsx, client/src/components/Layout.jsx, client/src/components/ProtectedRoute.jsx, client/src/contexts/AuthContext.jsx
modified loading statet on authcontext page
=> [CLUB-161] sync protected route with authcontext

client/src/components/FilterBar.jsx, client/src/pages/Events.jsx
- update the database (del capacity column, update events date)
- "past events" checkbox rename
- sorting past events by date
=> [CLUB-163] database update sorted all events

client/src/contexts/AuthContext.jsx
=> [CLUB-176] login-modal-fix

client/src/pages/Event.jsx, server/src/controllers/booking.controller.js, server/src/routes/booking.route.js, server/src/services/booking.service.js
- checks the user has already booked the event and change the button to RESERVE or RESERVED
=> [CLUB-163] - checked the event already booked 

client/src/components/ProfileCard.jsx, client/src/pages/AdminMember.jsx, server/src/controllers/users.controller.js, server/src/routes/admin.route.js, server/src/services/users.service.js
- create a separate isPayment status modifier button
- the button with true/false values sets the membership start date and end date.
- display the membership expiration date on the profile page
=> [CLUB-188] isPayed status button sets a new membership start date

client/src/components/AdminBookings.jsx, client/src/components/AdminMembers.jsx, client/src/components/AdminServiceBookingSearch.jsx, client/src/components/AdminServiceBookings.jsx, client/src/components/ProfileCard.jsx
Admin page -> multiple search
Profile page -> weekly list + button fix
=> [CLUB-186] admin multiple search

client/src/components/AdminBookings.jsx, server/src/services/admin.bookings.service.js
adminból az event törlés azonali, nem kell frissíteni az oldalt
=> event admin delete fix

client/src/components/AdminLayout.jsx, client/src/components/BookingWeeklyView.jsx, client/src/components/CurrentBookingWindow.jsx, client/src/index.scss, client/src/pages/Booking.jsx
- time slots size on the booking page
- set a message when there are no available time slots
- fix the height of the admin page
=> [CLUB-196] time slots bug fix
